version: 1.0.{build}
image: Visual Studio 2022
install:
- cmd: set PATH=C:\Program Files (x86)\MSBuild\15.0\Bin;%PATH%
cache: packages
before_build:
- cmd: nuget restore
build:
  verbosity: normal
test:
  categories:
    except:
    - Database